### ISSUE TITLE
preplaced mobs from other datapack-mods dying when near player?

### ISSUE THREAD

**Issue by nEONcReepER990** [NiceKaleido/NiceMobsRemastered#2]
Hello i encountered an issue with mobs in structure files? (idk, not a coder just know a lot) 
Mainly from 
**Additional Structures**_(shown in video)_ 
and 
**Explorify** _with their **Black Spiral** structure(piglins and piglin brutes)_ 
being killed when a player is near them _(10 - 15 block it seems)_.
And well i disabled your mod(only mod that modifies mobs in my mod folder) and they were fine, later in that video i again enabled it and it happed again.
I think maybe something to do with your health thing in the mod, idk.
(its not that crucial and you can live with it, its your mod you don't have to fix it bcs i image main compatibility is with vanilla.)

Awesome mod btw, thank you!

video (sorry for the quality just github limit :)
https://github.com/NiceKaleido/NiceMobsRemastered/assets/95697642/fa4ab902-af3f-4681-ba05-55f1a9457cd7

Edit: 
Still happens after update v2.2h
MC v1.21

**Comment by NiceKaleido** [comment]
Have you tried disabling the level system which changes entity health? 

This **might** happen due to the pre placed mobs not having enough health for it to work properly.

Thanks for the feedback

**Comment by nEONcReepER990** [comment]
I have not tried that because i want that feature to be active thanks tho, and also its a small thing it ain't that game breaking because it happens only sometimes _(i forgot to add to the edit)_ . I'll try disabling the level system when i get home.

**Comment by NiceKaleido** [comment]
Have been looking in this for the last couple of hours and I might have found a workaround. (Actually wanted to look into level scaling in general so that was quite fitting.)

The update is posted over at modrinth: https://modrinth.com/datapack/nice-mobs-remastered/version/2.2i
